version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - app_network

  backend:
    build: .
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build:
      context: G:/alibaba-dashboard-admin
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:3002" # Use 'backend' service name
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
